# Generated by Django 4.2.5 on 2023-10-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthNPassApp', '0004_userfamily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userFamily',
        ),
    ]
